// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webproject.Data;

#nullable disable

namespace Webproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808154425_AddMessages")]
    partial class AddMessages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Webproject.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Webproject.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Webproject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Webproject.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Webproject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Elegant golden ring",
                            ImageUrl = "/imgs/ring1.jpg",
                            Name = "Golden Ring",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Luxury diamond ring",
                            ImageUrl = "/imgs/ring2.jpg",
                            Name = "Diamond Ring",
                            Price = 450m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Beautiful silver ring",
                            ImageUrl = "/imgs/ring3.jpg",
                            Name = "Silver Ring",
                            Price = 180m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Premium royal ring",
                            ImageUrl = "/imgs/ring4.jpg",
                            Name = "Royal Ring",
                            Price = 600m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Premium diamond necklace",
                            ImageUrl = "/imgs/necklace1.jpg",
                            Name = "Diamond Necklace",
                            Price = 500m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Elegant gold necklace",
                            ImageUrl = "/imgs/necklace2.jpg",
                            Name = "Gold Necklace",
                            Price = 700m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Classic pearl necklace",
                            ImageUrl = "/imgs/necklace3.jpg",
                            Name = "Pearl Necklace",
                            Price = 350m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Luxury necklace",
                            ImageUrl = "/imgs/necklace4.jpg",
                            Name = "Luxury Necklace",
                            Price = 900m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Elegant diamond earrings",
                            ImageUrl = "/imgs/earring1.jpg",
                            Name = "Diamond Earrings",
                            Price = 300m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Beautiful gold earrings",
                            ImageUrl = "/imgs/earring2.jpg",
                            Name = "Gold Earrings",
                            Price = 250m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Classic pearl earrings",
                            ImageUrl = "/imgs/earring3.jpg",
                            Name = "Pearl Earrings",
                            Price = 200m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Premium luxury earrings",
                            ImageUrl = "/imgs/earring4.jpg",
                            Name = "Luxury Earrings",
                            Price = 550m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Elegant classic watch",
                            ImageUrl = "/imgs/watch1.jpg",
                            Name = "Classic Watch",
                            Price = 700m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Luxury gold watch",
                            ImageUrl = "/imgs/watch2.jpg",
                            Name = "Gold Watch",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Modern silver watch",
                            ImageUrl = "/imgs/watch3.jpg",
                            Name = "Silver Watch",
                            Price = 650m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Premium luxury watch",
                            ImageUrl = "/imgs/watch4.jpg",
                            Name = "Premium Watch",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Elegant golden bracelet",
                            ImageUrl = "/imgs/bracelet1.jpg",
                            Name = "Golden Bracelet",
                            Price = 400m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Luxury diamond bracelet",
                            ImageUrl = "/imgs/bracelet2.jpg",
                            Name = "Diamond Bracelet",
                            Price = 750m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Beautiful silver bracelet",
                            ImageUrl = "/imgs/bracelet3.jpg",
                            Name = "Silver Bracelet",
                            Price = 250m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Classic pearl bracelet",
                            ImageUrl = "/imgs/bracelet4.jpg",
                            Name = "Pearl Bracelet",
                            Price = 350m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Premium royal bracelet",
                            ImageUrl = "/imgs/bracelet5.jpg",
                            Name = "Royal Bracelet",
                            Price = 900m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Luxury gold design",
                            ImageUrl = "/imgs/bracelet6.jpg",
                            Name = "Luxury Gold Bracelet",
                            Price = 650m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Elegant crystal bracelet",
                            ImageUrl = "/imgs/bracelet7.jpg",
                            Name = "Crystal Bracelet",
                            Price = 500m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Classic everyday bracelet",
                            ImageUrl = "/imgs/bracelet8.jpg",
                            Name = "Classic Bracelet",
                            Price = 280m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Exclusive diamond bracelet",
                            ImageUrl = "/imgs/bracelet9.jpg",
                            Name = "Diamond Gold Bracelet",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Glamora",
                            Category = "Bracelets",
                            Description = "Modern elegant bracelet",
                            ImageUrl = "/imgs/bracelet10.jpg",
                            Name = "Modern Bracelet",
                            Price = 320m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Beautiful heart necklace",
                            ImageUrl = "/imgs/necklace5.jpg",
                            Name = "Heart Necklace",
                            Price = 280m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Royal diamond collection",
                            ImageUrl = "/imgs/necklace6.jpg",
                            Name = "Royal Diamond Necklace",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Elegant pearl style",
                            ImageUrl = "/imgs/necklace7.jpg",
                            Name = "Silver Pearl Necklace",
                            Price = 450m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Vintage luxury necklace",
                            ImageUrl = "/imgs/necklace8.jpg",
                            Name = "Vintage Necklace",
                            Price = 600m
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Classic diamond design",
                            ImageUrl = "/imgs/necklace9.jpg",
                            Name = "Classic Diamond Necklace",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Glamora",
                            Category = "Necklaces",
                            Description = "Rose gold elegance",
                            ImageUrl = "/imgs/necklace10.jpg",
                            Name = "Rose Gold Necklace",
                            Price = 800m
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Luxury black watch",
                            ImageUrl = "/imgs/watch5.jpg",
                            Name = "Luxury Black Watch",
                            Price = 850m
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Diamond premium watch",
                            ImageUrl = "/imgs/watch6.jpg",
                            Name = "Diamond Watch",
                            Price = 1700m
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Leather classic watch",
                            ImageUrl = "/imgs/watch7.jpg",
                            Name = "Classic Leather Watch",
                            Price = 450m
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Royal gold watch",
                            ImageUrl = "/imgs/watch8.jpg",
                            Name = "Royal Gold Watch",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Elegant crystal ring",
                            ImageUrl = "/imgs/ring5.jpg",
                            Name = "Crystal Ring",
                            Price = 320m
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Beautiful rose gold ring",
                            ImageUrl = "/imgs/ring6.jpg",
                            Name = "Rose Gold Ring",
                            Price = 380m
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Premium diamond ring",
                            ImageUrl = "/imgs/ring7.jpg",
                            Name = "Luxury Diamond Ring",
                            Price = 850m
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Classic silver ring",
                            ImageUrl = "/imgs/ring8.jpg",
                            Name = "Classic Silver Ring",
                            Price = 220m
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Royal luxury ring",
                            ImageUrl = "/imgs/ring9.jpg",
                            Name = "Royal Gold Ring",
                            Price = 950m
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Glamora",
                            Category = "Rings",
                            Description = "Vintage elegant ring",
                            ImageUrl = "/imgs/ring10.jpg",
                            Name = "Vintage Ring",
                            Price = 400m
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Elegant crystal earrings",
                            ImageUrl = "/imgs/earring5.jpg",
                            Name = "Crystal Earrings",
                            Price = 280m
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Beautiful rose gold earrings",
                            ImageUrl = "/imgs/earring6.jpg",
                            Name = "Rose Gold Earrings",
                            Price = 420m
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Premium diamond earrings",
                            ImageUrl = "/imgs/earring7.jpg",
                            Name = "Luxury Diamond Earrings",
                            Price = 850m
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Classic pearl earrings",
                            ImageUrl = "/imgs/earring8.jpg",
                            Name = "Golden Pearl Earrings",
                            Price = 500m
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Royal luxury earrings",
                            ImageUrl = "/imgs/earring9.jpg",
                            Name = "Royal Earrings",
                            Price = 900m
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Glamora",
                            Category = "Earrings",
                            Description = "Vintage elegant earrings",
                            ImageUrl = "/imgs/earring10.jpg",
                            Name = "Vintage Earrings",
                            Price = 350m
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Elegant luxury silver watch",
                            ImageUrl = "/imgs/watch9.jpg",
                            Name = "Luxury Silver Watch",
                            Price = 900m
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Glamora",
                            Category = "Watches",
                            Description = "Exclusive diamond royal watch",
                            ImageUrl = "/imgs/watch10.jpg",
                            Name = "Diamond Royal Watch",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("Webproject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Sara.Jamal11@gmail.com",
                            FullName = "SaraJamal",
                            Password = "11234511"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Lama.Hadi22@gmail.com",
                            FullName = "lamaHadi",
                            Password = "22134522"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Leen.Ahmad33@gmail.com",
                            FullName = "LeenAhmad",
                            Password = "33134533"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Sama.Kareem44@gmail.com",
                            FullName = "samakareem",
                            Password = "44134544"
                        });
                });

            modelBuilder.Entity("Webproject.Models.Message", b =>
                {
                    b.HasOne("Webproject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webproject.Models.Notification", b =>
                {
                    b.HasOne("Webproject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webproject.Models.Order", b =>
                {
                    b.HasOne("Webproject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webproject.Models.OrderDetail", b =>
                {
                    b.HasOne("Webproject.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webproject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
